### PR TITLE
SSL Valve Smarter whitespace parsing

### PR DESCRIPTION
**Pull request by lucasvc**
When using Nginx as load-balancer / endpoint SSL, it passes the certificate replacing new lines with multiple whitespaces, and the SSL valve current only replaces one white space character, so it doesn't recognize as a certificate.
Added unit tests.
[Related mailing post](http://www.mail-archive.com/users@tomcat.apache.org/msg122651.html).

### CODE REVIEW

**Comment by ChristopherSchultz** [comment]
-1 on the patch as it is:

1. It uses regular expressions on a critical path
2. It re-compiles a static regular expression on each request
3. It's a hack for Nginx-specific behavior but applies to all proxies (not just Nginx)

I'd like to see a benchmark of String.replace(' ', '\n') versus Pattern.matcher().replaceAll('\n') for this use-case. #1 above might not be so bad that it warrants a -1 all on its own.

If #1 is okay, then definitely use a precompiled and re-used Pattern object. I realize that this may have been an attempt to provide a minimal patch, but #2 above is a critical performance issue.

#3 is easily remedied by adding this as an optional behavior. Again, this may have been an attempt to provide a minimal patch. Please make this behavior optional by adding a configuration flag to the SSLValve to enable whitespace-merging.

**Comment by lucasvc** [comment]
About 1) and 2), you are completly right, it should be a precompiled `Pattern`, sorry for being so minimal patch.
I'll try to do the benchmark for 3 cases:

- `replace(char, char)` for each request
- `Pattern.matcher(String).replaceAll(String)` for each request
- Static precompiled `Pattern` and `match.replaceAll(String)` for each request

So 3), this is not a patch for Nginx, Nginx is where I found. IMHO this is being more robust with load-balancing: why only asume Apache `mod_proxy_http`?
Anyway, it is not hard to add as configurable, but again, IMHO basic processing should understand one or more whitespaces.

**Comment by markt-asf** [comment]
I'm looking at merging this into trunk (with subsequent back-ports) now.

The unit tests look to be overly complicated - particularly the solution to test the logging. I'm looking at alternative, hopefully simpler, approaches.

I also want to add a basic performance test to look at the options for implementing the replace.

**Comment by markt-asf** [comment]
The regular expression is significantly (I've seen values ranging from 5x to 40x) slower in my local testing.

Looking at this some more, and building on the work Chris Schultz did investigating the CertificateFactory,  there looks to be a simpler solution to this particular problem that allows the replacement to be removed entirely.

**Comment by markt-asf** [comment]
The simpler solution was applied.

**Pull request closed without merging**
